PROVINCES = 'provincias'
DEPARTMENTS = 'departamentos'
MUNICIPALITIES = 'municipios'
LOCALITIES = 'localidades'
STREETS = 'calles'

RAW_TABLE_NAME = 'raw_{}'
ETL_TABLE_NAME = 'georef_{}'

PROVINCES_ETL_TABLE = ETL_TABLE_NAME.format(PROVINCES)
DEPARTMENTS_ETL_TABLE = ETL_TABLE_NAME.format(DEPARTMENTS)
MUNICIPALITIES_ETL_TABLE = ETL_TABLE_NAME.format(MUNICIPALITIES)
LOCALITIES_ETL_TABLE = ETL_TABLE_NAME.format(LOCALITIES)
STREETS_ETL_TABLE = ETL_TABLE_NAME.format(STREETS)

PROVINCES_RAW_TABLE = RAW_TABLE_NAME.format(PROVINCES)
DEPARTMENTS_RAW_TABLE = RAW_TABLE_NAME.format(DEPARTMENTS)
MUNICIPALITIES_RAW_TABLE = RAW_TABLE_NAME.format(MUNICIPALITIES)
LOCALITIES_RAW_TABLE = RAW_TABLE_NAME.format(LOCALITIES)
STREETS_RAW_TABLE = RAW_TABLE_NAME.format(STREETS)

PROVINCE_ID_LEN = 2
DEPARTMENT_ID_LEN = 5
MUNICIPALITY_ID_LEN = 6
LOCALITY_ID_LEN = 11
STREET_ID_LEN = 13

STREETS_SOURCE = 'INDEC'
