version: '3.9'
services:
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile_db
    image: datosgobar/georef-etl_db
    container_name: georef-etl_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME_TEST: ${DB_NAME_TEST}
      DB_USER_TEST: ${DB_USER_TEST}
      DB_PASSWORD_TEST: ${DB_PASSWORD_TEST}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./docker/init-user-db_test.sh:/docker-entrypoint-initdb.d/init-user-db_test.sh
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$DB_PASSWORD pg_isready -U $DB_USER -d $DB_NAME -q"]
      interval: 10s
      retries: 5
    networks:
      - geonet
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_app
    image: datosgobar/georef-etl_app
    container_name: georef-etl_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./config:/opt/app-root/src/georef-ar-etl/config:ro
      - ./files:/opt/app-root/src/georef-ar-etl/files
      - ./reports:/opt/app-root/src/georef-ar-etl/reports
      - ./tests/test_files:/opt/app-root/src/georef-ar-etl/tests/test_files
    networks:
      - geonet
volumes:
  dbdata:
  dbdatatest:
networks:
  geonet:
