#!/usr/bin/env bash
export DEBUG=
export DJANGO_SECRET_KEY=''
export GEOREF_API_URL=
export GEOREF_DB_HOST=
export GEOREF_DB_NAME=
export GEOREF_DB_USER=
export GEOREF_DB_PASS=
export POSTGRES_HOST=
export POSTGRES_DBNAME=
export POSTGRES_USER=
export POSTGRES_PASSWORD=
