export DJANGO_ENVIRONMENT=
export DJANGO_SECRET_KEY=
export GEOREF_API_URL=
export GEOREF_DB_USER=
export GEOREF_DB_PASS=
export POSTGRES_HOST=
export POSTGRES_DBNAME=
export POSTGRES_USER=
export POSTGRES_PASSWORD=
export KONG_URL=
export KONG_DB_USER=
export KONG_DB_PASS=
export KONG_HOST=
export HERE_APP_CODE=
export HERE_APP_ID=

