# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('road_name', models.CharField(blank=True, max_length=100, null=True)),
                ('road_type', models.CharField(blank=True, max_length=25, null=True)),
                ('door_number', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Locality')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State')),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
