# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'búsqueda'},
        ),
        migrations.AlterField(
            model_name='search',
            name='door_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='altura'),
        ),
        migrations.AlterField(
            model_name='search',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Locality', verbose_name='localidad'),
        ),
        migrations.AlterField(
            model_name='search',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='search',
            name='road_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='search',
            name='road_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='tipo de camino'),
        ),
        migrations.AlterField(
            model_name='search',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='search',
            name='text',
            field=models.CharField(max_length=250, verbose_name='texto de búsqueda'),
        ),
    ]
