# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('agglomerate', models.CharField(blank=True, max_length=4, null=True, verbose_name='aglomerado')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'localidad',
                'verbose_name_plural': 'localidades',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('road_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='tipo de camino')),
                ('start_left', models.IntegerField(blank=True, null=True, verbose_name='inicio izquierda')),
                ('start_right', models.IntegerField(blank=True, null=True, verbose_name='inicio derecha')),
                ('end_left', models.IntegerField(blank=True, null=True, verbose_name='fin izquierda')),
                ('end_right', models.IntegerField(blank=True, null=True, verbose_name='fin derecha')),
                ('geom', models.TextField(blank=True, null=True, verbose_name='geometría')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='código postal')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Locality', verbose_name='localidad')),
            ],
            options={
                'verbose_name': 'calle',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'provincia',
            },
        ),
        migrations.AddField(
            model_name='road',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='department',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
    ]
