# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'departamento'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'localidad', 'verbose_name_plural': 'localidades'},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': 'calle'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'provincia'},
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='agglomerate',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='aglomerado'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='road',
            name='code',
            field=models.CharField(max_length=13, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='road',
            name='end_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='fin izquierda'),
        ),
        migrations.AlterField(
            model_name='road',
            name='end_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='fin derecha'),
        ),
        migrations.AlterField(
            model_name='road',
            name='geom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='geometría'),
        ),
        migrations.AlterField(
            model_name='road',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Locality', verbose_name='localidad'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=5, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='road',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='código postal'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='tipo de camino'),
        ),
        migrations.AlterField(
            model_name='road',
            name='start_left',
            field=models.IntegerField(blank=True, null=True, verbose_name='inicio izquierda'),
        ),
        migrations.AlterField(
            model_name='road',
            name='start_right',
            field=models.IntegerField(blank=True, null=True, verbose_name='inicio derecha'),
        ),
        migrations.AlterField(
            model_name='road',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre'),
        ),
    ]
