# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0002_auto_20170810_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='timestamp',
        ),
    ]
