# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0002_consumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('bahra_type', models.CharField(blank=True, choices=[('E', 'Entidad (E)'), ('LC', 'Componente de localidad compuesta (LC)'), ('LS', 'Localidad simple (LS)')], max_length=3, null=True, verbose_name='tipo')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=1000, verbose_name='latitud')),
                ('lon', models.DecimalField(decimal_places=10, max_digits=1000, verbose_name='longitud')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia')),
            ],
            options={
                'verbose_name': 'entidad bahra',
                'verbose_name_plural': 'entidades bahra',
            },
        ),
        migrations.AlterModelOptions(
            name='consumer',
            options={'verbose_name': 'consumidor', 'verbose_name_plural': 'consumidores'},
        ),
    ]
