# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-08 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0003_auto_20171107_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=1000, verbose_name='latitud')),
                ('lon', models.DecimalField(decimal_places=10, max_digits=1000, verbose_name='longitud')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia')),
            ],
            options={
                'verbose_name': 'municipio',
            },
        ),
    ]
