# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-02 14:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0004_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='lon',
        ),
        migrations.AddField(
            model_name='department',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='municipality',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='settlement',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='state',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
