# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0005_auto_20180202_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento'),
        ),
    ]
