# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-21 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0006_municipality_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='longitud'),
            preserve_default=False,
        ),
    ]
