# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0007_auto_20180221_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Municipality', verbose_name='municipalidad'),
        ),
    ]
