# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-13 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0009_auto_20180320_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
