# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-13 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0009_auto_20180320_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='department',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='state',
        ),
        migrations.RemoveField(
            model_name='road',
            name='locality',
        ),
        migrations.AddField(
            model_name='road',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
        migrations.DeleteModel(
            name='Locality',
        ),
    ]
