# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0011_auto_20180831_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='department_intersection_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='porcentaje intersección departamento'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='department_area_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='porcentaje area departamento'),
        ),
    ]
