# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0012_auto_20180919_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='state_intersection',
            field=models.FloatField(blank=True, null=True, verbose_name='intersección'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='state_intersection',
            field=models.FloatField(blank=True, null=True, verbose_name='intersección'),
        ),
    ]
