# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0013_auto_20181011_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='code',
            field=models.CharField(max_length=13, unique=True, verbose_name='código'),
        ),
    ]
