# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-10 11:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0014_auto_20181227_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('iso_code', models.CharField(blank=True, max_length=4, verbose_name='codigo iso')),
                ('iso_name', models.CharField(blank=True, max_length=100, verbose_name='nombre iso')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitud')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitud')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='road',
            name='road_type',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='bahra_type',
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='name_short',
            field=models.CharField(default='', max_length=100, verbose_name='nombre corto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='source',
            field=models.CharField(default='', max_length=50, verbose_name='fuente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='name_short',
            field=models.CharField(default='', max_length=100, verbose_name='nombre corto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='source',
            field=models.CharField(default='', max_length=50, verbose_name='fuente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='category',
            field=models.CharField(default='', max_length=25, verbose_name='tipo de camino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='locality_code',
            field=models.CharField(default='', max_length=8, verbose_name='código localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='road',
            name='source',
            field=models.CharField(default='', max_length=50, verbose_name='fuente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='category',
            field=models.CharField(choices=[('E', 'Entidad (E)'), ('LC', 'Componente de localidad compuesta (LC)'), ('LS', 'Localidad simple (LS)')], default='', max_length=3, verbose_name='categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settlement',
            name='source',
            field=models.CharField(default='', max_length=50, verbose_name='fuente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='iso_code',
            field=models.CharField(default='', max_length=4, verbose_name='código iso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='iso_name',
            field=models.CharField(default='', max_length=100, verbose_name='nombre iso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='name_short',
            field=models.CharField(default='', max_length=100, verbose_name='nombre corto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='source',
            field=models.CharField(default='', max_length=50, verbose_name='fuente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='department',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='department',
            name='state_intersection',
            field=models.FloatField(verbose_name='intersección'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='state_intersection',
            field=models.FloatField(verbose_name='intersección'),
        ),
        migrations.AlterField(
            model_name='road',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='road',
            name='geom',
            field=models.TextField(verbose_name='geometría'),
        ),
        migrations.AlterField(
            model_name='road',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='code',
            field=models.CharField(max_length=11, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Department', verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo_admin.State', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='state',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
