# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0014_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='longitud'),
            preserve_default=False,
        ),
    ]
