# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-15 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_admin', '0016_auto_20190110_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='código'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_short',
            field=models.CharField(default='', max_length=100, verbose_name='nombre corto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='fuente'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='geo_admin.Country', verbose_name='país'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='codigo iso'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre iso'),
        ),
    ]
