version: '2.4'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    image: datosgobar/georef-etl_db
    container_name: georef_etl_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -q -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
    networks:
      - geonet
  db-test:
    build:
      context: .
      dockerfile: Dockerfile_db
    image: datosgobar/georef-etl_db_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-U', 'georef', '-d', 'georef_ar_etl_test']
      interval: 10s
    networks:
      - geonet
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile_app
    image: datosgobar/georef-etl_app
    container_name: georef_etl_app
    command: tail -F anything
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../config:/opt/app-root/src/georef-ar-etl/config:ro
      - ../files:/opt/app-root/src/georef-ar-etl/files
      - ../reports:/opt/app-root/src/georef-ar-etl/reports
    networks:
      - geonet
volumes:
  dbdata:
networks:
  geonet:
