FROM python:3.6.15-slim-buster

RUN apt-get update && apt-get install -y gdal-bin libpq-dev gcc python3-dev && apt-get install -y python3-psycopg2 make

RUN pip install --upgrade pip

WORKDIR /opt/app-root/src/georef-ar-etl

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD make migrate && make run