FROM postgres:17-bullseye

RUN localedef -i es_AR -c -f UTF-8 -A /usr/share/locale/locale.alias es_AR.UTF-8
ENV LANG es_AR.utf8

RUN apt-get update && apt-get install -y postgresql-17-postgis-3 postgresql-17-postgis-3-scripts && rm -rf /var/lib/apt/lists/*

COPY docker/init-user-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
