"""
Django settings for georef project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/
DEBUG = os.environ.get('DEBUG')
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django_extensions',
    'geo_admin',
]

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

GEOREF = {
    'ENGINE': 'django.contrib.gis.db.backends.postgis',
    'NAME': os.environ.get('GEOREF_DB_NAME'),
    'USER': os.environ.get('GEOREF_DB_USER'),
    'PASSWORD': os.environ.get('GEOREF_DB_PASS'),
    'HOST': os.environ.get('GEOREF_DB_HOST'),
    'PORT': '5432',
}

DATABASES = {'default': GEOREF}
