"""Modifica relaciones de calles y localidades

Revision ID: 2586af954886
Revises: c708897ab55b
Create Date: 2025-06-02 09:07:52.306009

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '2586af954886'
down_revision = 'c708897ab55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_calles', sa.Column('localidad_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'georef_calles', 'georef_localidades', ['localidad_id'], ['id'], ondelete='cascade')
    op.drop_column('georef_calles', 'loc_nombre')
    op.drop_column('georef_calles', 'loc_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_calles', sa.Column('loc_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('georef_calles', sa.Column('loc_nombre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'georef_calles', type_='foreignkey')
    op.drop_column('georef_calles', 'localidad_id')
    # ### end Alembic commands ###
