"""Agrega establecimientos educativos

Revision ID: 32642dde5a4a
Revises: 2586af954886
Create Date: 2025-06-23 17:41:18.860938

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '32642dde5a4a'
down_revision = '2586af954886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('georef_establecimientos_educativos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('domicilio', sa.String(), nullable=False),
    sa.Column('gestion', sa.String(), nullable=False),
    sa.Column('niveles', sa.String(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=4326), nullable=False),
    sa.Column('provincia_id', sa.String(), nullable=False),
    sa.Column('departamento_id', sa.String(), nullable=False),
    sa.Column('gobierno_local_id', sa.String(), nullable=True),
    sa.Column('asentamiento_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asentamiento_id'], ['georef_asentamientos.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['departamento_id'], ['georef_departamentos.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['gobierno_local_id'], ['georef_gobiernos_locales.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['provincia_id'], ['georef_provincias.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('georef_establecimientos_educativos')
    # ### end Alembic commands ###
