"""empty message

Revision ID: 473fefa4c4b0
Revises: 7cedddd7547a
Create Date: 2023-10-08 00:15:26.036653

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '473fefa4c4b0'
down_revision = '7cedddd7547a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('georef_municipios', 'geometria',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326),
                    type_=geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('georef_municipios', 'geometria',
                    existing_type=geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326),
                    type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326),
                    nullable=False)
    # ### end Alembic commands ###
