"""Add locality params to street

Revision ID: 4e2f459436e4
Revises: 90077a8f7b48
Create Date: 2024-12-28 18:18:59.998638

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4e2f459436e4'
down_revision = '90077a8f7b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_calles', sa.Column('loc_id', sa.String(), nullable=True))
    op.add_column('georef_calles', sa.Column('loc_nombre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('georef_calles', 'loc_nombre')
    op.drop_column('georef_calles', 'loc_id')
    # ### end Alembic commands ###
