"""Agrega instituciones universitarias

Revision ID: 4ed0ee5350b2
Revises: c6e02a189e6e
Create Date: 2025-06-24 13:55:22.345601

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4ed0ee5350b2'
down_revision = 'c6e02a189e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('georef_instituciones_universitarias',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('domicilio', sa.String(), nullable=False),
    sa.Column('localidad', sa.String(), nullable=True),
    sa.Column('gestion', sa.String(), nullable=False),
    sa.Column('niveles', sa.String(), nullable=False),
    sa.Column('universidad', sa.String(), nullable=False),
    sa.Column('unidad_academica', sa.String(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=4326), nullable=False),
    sa.Column('provincia_id', sa.String(), nullable=False),
    sa.Column('departamento_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['georef_departamentos.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['provincia_id'], ['georef_provincias.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('georef_instituciones_universitarias')
    # ### end Alembic commands ###
