"""empty message

Revision ID: 7bf4811afc85
Revises: c9fcf57e8627
Create Date: 2024-11-12 20:54:08.615620

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7bf4811afc85'
down_revision = 'c9fcf57e8627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'georef_localidades',
        'geometria',
        type_=geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326),
        existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=4326),
        nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'georef_localidades', 'geometria',
        type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=4326),
        existing_type=geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326),
        nullable=False)
    # ### end Alembic commands ###
