"""Add census locality foreign keys

Revision ID: 7cedddd7547a
Revises: 1e686223eafb
Create Date: 2019-05-01 14:28:04.300111

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '7cedddd7547a'
down_revision = '1e686223eafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_asentamientos', sa.Column('localidad_censal_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'georef_asentamientos', 'georef_localidades_censales', ['localidad_censal_id'], ['id'], ondelete='cascade')
    op.add_column('georef_calles', sa.Column('localidad_censal_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'georef_calles', 'georef_localidades_censales', ['localidad_censal_id'], ['id'], ondelete='cascade')
    op.add_column('georef_localidades', sa.Column('localidad_censal_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'georef_localidades', 'georef_localidades_censales', ['localidad_censal_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'georef_localidades', type_='foreignkey')
    op.drop_column('georef_localidades', 'localidad_censal_id')
    op.drop_constraint(None, 'georef_calles', type_='foreignkey')
    op.drop_column('georef_calles', 'localidad_censal_id')
    op.drop_constraint(None, 'georef_asentamientos', type_='foreignkey')
    op.drop_column('georef_asentamientos', 'localidad_censal_id')
    # ### end Alembic commands ###
