"""Cambia geometría a MultiPolygon en LocalGovernment

Revision ID: 8c0660b2c683
Revises: 4e2f459436e4
Create Date: 2025-04-14 14:53:36.960854

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8c0660b2c683'
down_revision = '4e2f459436e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('georef_gobiernos_locales', 'geometria',
               existing_type=geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326),
               type_=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('georef_gobiernos_locales', 'geometria',
               existing_type=geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326),
               type_=geoalchemy2.types.Geometry(geometry_type='GEOMETRY', srid=4326),
               nullable=True)
    # ### end Alembic commands ###
