"""Modifica modelo de establecimientos educativos

Revision ID: c6e02a189e6e
Revises: 32642dde5a4a
Create Date: 2025-06-24 12:42:04.367110

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c6e02a189e6e'
down_revision = '32642dde5a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_establecimientos_educativos', sa.Column('localidad', sa.String(), nullable=True))
    op.drop_constraint('georef_establecimientos_educativos_gobierno_local_id_fkey', 'georef_establecimientos_educativos', type_='foreignkey')
    op.drop_constraint('georef_establecimientos_educativos_asentamiento_id_fkey', 'georef_establecimientos_educativos', type_='foreignkey')
    op.drop_column('georef_establecimientos_educativos', 'gobierno_local_id')
    op.drop_column('georef_establecimientos_educativos', 'asentamiento_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_establecimientos_educativos', sa.Column('asentamiento_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('georef_establecimientos_educativos', sa.Column('gobierno_local_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('georef_establecimientos_educativos_asentamiento_id_fkey', 'georef_establecimientos_educativos', 'georef_asentamientos', ['asentamiento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('georef_establecimientos_educativos_gobierno_local_id_fkey', 'georef_establecimientos_educativos', 'georef_gobiernos_locales', ['gobierno_local_id'], ['id'], ondelete='CASCADE')
    op.drop_column('georef_establecimientos_educativos', 'localidad')
    # ### end Alembic commands ###
