"""Incorpora unidades geoestadísticas

Revision ID: c708897ab55b
Revises: 8c0660b2c683
Create Date: 2025-05-15 11:39:43.634164

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'c708897ab55b'
down_revision = '8c0660b2c683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('georef_aglomerados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('georef_fracciones_censales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('provincia_interseccion', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326), nullable=False),
    sa.Column('provincia_id', sa.String(), nullable=False),
    sa.Column('departamento_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['georef_departamentos.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['provincia_id'], ['georef_provincias.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('georef_radios_censales',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fuente', sa.String(), nullable=False),
    sa.Column('fraccion_censal_interseccion', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('geometria', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326), nullable=False),
    sa.Column('provincia_id', sa.String(), nullable=False),
    sa.Column('departamento_id', sa.String(), nullable=False),
    sa.Column('fraccion_censal_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['georef_departamentos.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['fraccion_censal_id'], ['georef_fracciones_censales.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['provincia_id'], ['georef_provincias.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('georef_radios_censales')
    op.drop_table('georef_fracciones_censales')
    op.drop_table('georef_aglomerados')
    # ### end Alembic commands ###
