"""Add loc_id and loc_nombre to streets

Revision ID: fdb64e04deee
Revises: fe67a4fa0a75
Create Date: 2024-11-14 21:06:29.895278

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fdb64e04deee'
down_revision = 'fe67a4fa0a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_calles', sa.Column('loc_id', sa.String(), nullable=True))
    op.add_column('georef_calles', sa.Column('loc_nombre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('georef_calles', 'loc_id')
    op.drop_column('georef_calles', 'loc_nombre')
    # ### end Alembic commands ###
