"""empty message

Revision ID: fe67a4fa0a75
Revises: 7bf4811afc85
Create Date: 2024-11-13 14:44:33.125164

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fe67a4fa0a75'
down_revision = '7bf4811afc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('georef_cuadras', sa.Column('loc_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'georef_cuadras', 'georef_localidades', ['loc_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'georef_cuadras', type_='foreignkey')
    op.drop_column('georef_cuadras', 'loc_id')
    # ### end Alembic commands ###
