# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170315_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='search_text',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
